# ============================================================================
# RESTRICTED USE -- All rights reserved.
# The data, experimental results, and source code in this repository are
# provided for archival / reproducibility reference only. No part of the
# data, experiments, or code may be used, copied, modified, redistributed,
# or incorporated into other works without the author's explicit written
# permission. See LICENSE and NOTICE.md.
# ============================================================================

import pandas as pd 
import matplotlib .pyplot as plt 

# Global drawing parameters adapted to academic display
plt .rcParams ["font.sans-serif"]=["SimHei"]
plt .rcParams ["axes.unicode_minus"]=False 
plt .rcParams ["figure.dpi"]=300 

# Read the monthly total summary indicator file generated by the 05 script
df =pd .read_csv (r"D:\study\test1\month_total_agg_gcs.csv",encoding ="utf-8-sig")
# Time format conversion and sorting in ascending order of time
df ["month"]=pd .to_datetime (df ["month"])
df =df .sort_values ("month")

# New canvas
fig ,ax =plt .subplots (figsize =(10 ,5 ))

# Draw two polylines and fix the color matching to facilitate unified layout of the journal.
ax .plot (df ["month"],df ["gcs_base"],color ="#1f77b4",linewidth =1.7 ,label ="Benchmark GCSt index (word frequency caliber)")
ax .plot (df ["month"],df ["gcs_tfidf_weighted"],color ="#ff7f0e",linestyle ="--",linewidth =1.7 ,label ="TF-IDF Weighted GCSt Index")

# 0 value reference line to distinguish the strength of GPU/CPU narrative
ax .axhline (y =0 ,color ="black",linestyle ="-.",alpha =0.5 )

# axis labels
ax .set_xlabel ("年月")
ax .set_ylabel ("GCSt Competitive Sentiment Index")

# Legend, grid settings
ax .legend (frameon =False )
ax .grid (alpha =0.25 ,linestyle =":")

# Adaptive layout, save vector PDF files
plt .tight_layout ()
plt .savefig (r"D:\study\test1\fig_gcst_tfidf_contrast.pdf")
plt .show ()

print ("✅ Double indicator comparison timing chart output completed")
print ("使用数据源：month_total_agg_gcs.csv（05月度词汇总量聚合口径）")